--- 
- name: "configuration play."
  hosts: '*'
- 
  apt: 
    upgrade: "yes"
  become: true
  name: "upgrade packages."
- 
  apt: 
    name: 
      - nodejs
      - npm
    state: latest
    update_cache: true
  become: true
  name: "install dependencies."
- 
  become: true
  name: "install pm2"
  npm: 
    global: true
    name: pm2
    production: true
    state: present
- 
  git: 
    dest: /src/project
    repo: "https://github.com/ndakena/Give-your-app-supper-powers.git"
    version: master
  name: "Clone git repo"
- 
  name: "Run backend"
  shell: "cd /src/project/backend &&  npm i && pm2 startup && pm2 start npm --name \"backend\" -- start"
