--- 
- name: "wait 600 seconds for target connection to become reachable/usable."
  wait_for_connection:
- 
  apt: 
    upgrade: "yes"
  become: true
  name: "upgrade packages."
- 
  apt: 
    name: 
      - nodejs
      - npm
    state: latest
    update_cache: true
  become: true
  name: "install dependencies."
- 
  become: true
  name: "install pm2"
  npm: 
    global: true
    name: pm2
    production: true
    state: present
- 
  environment: 
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_DATABASE: circleci-db
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: circleci-db
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_PASSWORD: CircleciDB
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: circleci-db
  name: "Set environmental variables"
- 
  git: 
    dest: /src/project
    repo: "https://github.com/ndakena/Give-your-app-supper-powers.git"
    version: master
  name: "Clone git repo"
- 
  name: "Run backend"
  shell: "cd /src/project/backend &&  npm i && pm2 startup && pm2 start npm --name \"backend\" -- start"
