---
- name: "configuration play."
  hosts: webservers
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python36
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python36
      raw: yum -y install python36
      when: check_python.rc != 0

    - setup:
  roles:
    - configure-server
