---
- name: "configuration play."
  hosts: webservers
  user: ubuntu

  pre_tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python
      raw: yum -y install python
      when: check_python.rc != 0

    - setup:
  roles:
    - configure-server
