---
- name: "configuration play."
  hosts: webservers
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python36
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "install python for Ansible."
      become: true
      raw: (apt -y update && apt install -y python36) || test -e /usr/bin/python36
      changed_when: false

    - setup:
  roles:
    - configure-server
