---
- name: Install 
  hosts: "webservers"
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - debug: var=ansible_host
    - name: run as root - update, install python, ...
      ignore_errors: true
      raw: "{{ item }}"
      loop:
        - touch /root/ansible-apt-update
        - apt -y update
        - apt -y upgrade
        - apt install -y python

- roles:
   - configure-server
